input_features:
  - name: Pclass
    type: category
  - name: Sex
    type: category
  - name: Age
    type: number
  - name: SibSp
    type: number
  - name: Parch
    type: number
  - name: Fare
    type: number
  - name: Embarked
    type: category

output_features:
  - name: Survived
    type: binary

trainer:
  epochs: 30
 
