version: '3.8'

services:
  ml-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./predictions:/app/predictions
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
    restart: unless-stopped

